### ISSUE TITLE
error on Lolipop

### ISSUE THREAD

**Issue by emailmore** [raduetsya/2048#1]
I tried this on my old kitkat & it is really impressive, but when I tried this game on my new Lolipop hanset. I am facing problem. I much newbies for android & failed to solve the issue. I very mush like your efforts & posting this as a small help for serve others.
![error](https://cloud.githubusercontent.com/assets/10777994/5982250/46440bf8-a8e7-11e4-86d9-1bf7cf18b369.png)

**Comment by emailmore** [comment]
hey did you work out this issue

**Comment by raduetsya** [comment]
Fixed
